### ISSUE TITLE
Migrate redirect to raise an exception

### ISSUE THREAD

**Issue by BradMclain** [anomaly/prestans#102]
Is this a valid thing for a REST service to do?

If we decide to keep we need to make sure our encoding is correct to work with all WSGI providers.

**Comment by devraj** [comment]
REST services are still in theory a URL that provide a certain type of content. i.e URL. It can then be argued that a `301` response especially from a `GET` handler should be considered valid. That is to say that the API end point is declaring that this URL is no longer valid.

However the appropriate response is to send this redirect notification to the client who should then make the decision to request the new URL. This is how a browser and Web server would negotiate redirections.

**Comment by BradMclain** [comment]
Decided to keep this but to migrate it to use exceptions.
