### ISSUE TITLE
(BREAKING CHANGE) regex matches should match against the PATH_INFO environ variable, not the webob request.path

### ISSUE THREAD

**Issue by coderatchet** [anomaly/prestans#126]
Currently, Apache configurations containing WSGIScriptAlias directives will not pass path information correctly as Prestans require the WSGIScriptAliasMatch directive as described [here](https://prestans.readthedocs.io/en/latest/handlers.html#using-request-router?highlight=wsgiscriptaliasmatch)

According to @GrahamDumpleton himself in [this thread](https://github.com/GrahamDumpleton/mod_wsgi/issues/149), A saner approach would be to use the WSGIScriptAlias directive as the correct PATH_INFO will then be passed to the script. Using our currently documented way results in the entire url being passed in as the SCRIPT_NAME which, as the variable name reads, does not do seem to be it's intended purpose.

**Comment by GrahamDumpleton** [comment]
I'll try and summarise what would be typical and you can then see how that matches.

A WSGI application would be mounted at a specific mount point on the web server. Often this is at the root of the site. In the case of it being mounted at the root of the site, you would end up being passed:

```
SCRIPT_NAME = ''
PATH_INFO = '/appurl'
```

If it was mounted at a sub URL, such as with:

```
WSGIScrtipAlias /mountpoint /some/path.app.wsgi
```

you would end being passed:

```
SCRIPT_NAME = '/mountpoint'
PATH_INFO = '/appurl'
```

The internal routing done by the WSGI application would then normally only be based on the ``PATH_INFO`` and not match the mount point specified by ``SCRIPT_NAME``.

If the application need to create absolute URLs for redirects etc, then it would use the algorithm at:

* http://legacy.python.org/dev/peps/pep-3333/#url-reconstruction

This would add make in ``SCRIPT_NAME`` as necessary.

If you use:

```
WSGIScriptAliasMatch ^/mountpoint/(*) /some/path.app.wsgi
```

you get passed:

```
SCRIPT_NAME = '/mountpoint/appurl'
PATH_INFO = ''
```

So this is not at all typical. It would mean the application routing would have to include the mount point, which means then that the application is not easily portable and mountable at different mount points as the URL routing rules would need to change.

**Comment by coderatchet** [comment]
@GrahamDumpleton Thanks!
