### ISSUE TITLE
Investigation of Cache in REST handler

### ISSUE THREAD

**Issue by BradMclain** [anomaly/prestans#13]
parameter set -> get_cache_key

**Comment by devraj** [comment]
After extended discussions with @BradMclain caching is very specific to the application and the backend it employs. This might be outside the scope of a project like prestans and might be the real of caching for backends like NDB or using [dogpile](https://dogpilecache.readthedocs.org/en/latest/api.html#dogpile.cache.region.make_region) for relational databases.

Even if the the writable response could be cached, complex authorisation rules would require accessing the backend per request. This would negate a swift response from the handler.

At present this has been deferred to be in the realm of the server or database environment.
