### ISSUE TITLE
Upgrading from 2.0.16 to 2.0.17 breaks the way URLs are evaluated

### ISSUE THREAD

**Issue by devraj** [anomaly/prestans#141]
- If this is a breaking release then we should move the version to `2.1.0`
- Document what breaks the URL evaluation

**Comment by devraj** [comment]
- Update release to `2.1.0`
- Caused to due #126 
- Update documentation as a result

**Comment by coderatchet** [comment]
if your httpd.conf file contains the WSGIScriptAlias directive like this:

```
WSGIScriptAlias /some/mountpoint /scripts/some_app.wsgi
WSGIScriptAlias /other/mountpoint /scripts/other_app.wsgi
``` 

`some_app.wsgi` and `other_app.wsgi` applications should include routes that handle what occurs after the url-path mentioned in the WSGIScriptAlias's first argument.

for example: If some_app.wsgi supplied a Router with the following definitions:

```python
application = RequestRouter([
    (r'/foo/bar', some.HandlerClass),
    ...
])
```

Then a call of `GET /some/mountpoint/foo/bar` to the host defined with the above `httpd.conf` should resolve the `some.HandlerClass` in `some_app.wsgi`
