### ISSUE TITLE
Investigate performance of adapting models

### ISSUE THREAD

**Issue by brendon1555** [anomaly/prestans#153]
Discovered when working on another project. Adapting multiple instances in a loop took a long time to process.

**Comment by devraj** [comment]
From what I can see I think this is to do with adapters using `getattr` and not `self.__dict__`. As a broader issue we should also think about how we can measure performance and read more on what makes Python apps perform better.

**Comment by devraj** [comment]
This has also only ever been noticed on `Oracle` as the backend. Further investigation on backends to be performed before this is labelled as an issue with prestans
