### ISSUE TITLE
Run pylint over the entire codebase

### ISSUE THREAD

**Issue by devraj** [anomaly/prestans#78]
List of files to migrate:
- [x] `prestans/__init__.py`
- [x] `prestans/deserializer.py`
- [ ] `prestans/devel/__init__.py`
- [x] `prestans/devel/exception.py`
- [x] `prestans/devel/gen/__init__.py`
- [x] `prestans/devel/gen/closure.py`
- [x] `prestans/devel/gen/templates/__init__.py`
- [x] `prestans/devel/gen/templates/closure/__init__.py`
- [x] `prestans/devel/serve.py`
- [x] `prestans/exception.py`
- [x] `prestans/ext/__init__.py`
- [x] `prestans/ext/analytics/__init__.py`
- [x] `prestans/ext/appengine.py`
- [x] `prestans/ext/data/__init__.py`
- [x] `prestans/ext/data/adapters/__init__.py`
- [x] `prestans/ext/data/adapters/ndb.py`
- [x] `prestans/ext/data/adapters/sqlalchemy.py`
- [x] `prestans/http.py`
- [ ] `prestans/parser.py`
- [x] `prestans/provider/__init__.py`
- [x] `prestans/provider/auth.py`
- [x] `prestans/provider/cache.py`
- [x] `prestans/provider/throttle.py`
- [ ] `prestans/rest.py`
- [x] `prestans/serializer.py`
- [x] `prestans/testsuite/__init__.py`
- [x] `prestans/testsuite/types.py`
- [ ] `prestans/types.py`
- [x] `setup.py`

**Comment by BradMclain** [comment]
Will be covered in 3.0.0 release.
