### ISSUE TITLE
The dev package requires jinja2

### ISSUE THREAD

**Issue by BradMclain** [anomaly/prestans#99]
Should we add it as a requirement in `setup.py`?

**Comment by devraj** [comment]
Should the `devel` package and cli tools be different distributions; i'd like to think that we don't install `devel` on production servers.

**Comment by devraj** [comment]
I think it should yes.

**Comment by BradMclain** [comment]
Will be able to install using syntax `pip install prestans` on server or `pip install prestans[devel]` for development.
